name: 'Hello World'
description: 'Greet someone'

outputs:
  build_number:
    description: "Random number"
    value: ${{ steps.build_number.outputs.myMask }}

runs:
  using: "composite"
  steps:
    - name: Set variables
      id: build_number
      shell: pwsh
      run: |
        $myMask="$(date +'%Y.%m.%d').${{ github.run_number }}"
        echo "$myMask"
        echo "::add-mask::$myMask"
        echo "myMask=$myMask" >> $env:GITHUB_OUTPUT
